#ifndef RESOURCE_H
#define RESOURCE_H

#define VER_MAJOR 3
#define VER_MINOR 0
#define VER_PATCH 0
#define VER_BUILD 0

#define STRINGIFY2(x) #x
#define STRINGIFY(x) STRINGIFY2(x)

#define VER_FILE_VERSION        VER_MAJOR,VER_MINOR,VER_PATCH,VER_BUILD
#define VER_FILE_VERSION_STR    STRINGIFY(VER_MAJOR) "." STRINGIFY(VER_MINOR) "." STRINGIFY(VER_PATCH) ".0"

#endif
