#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OnlinePrivilegeChecker

#include "Basic.hpp"

#include "UnionSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OnlinePrivilegeChecker.BP_OnlinePrivilegeChecker_C
// 0x0008 (0x0300 - 0x02F8)
class ABP_OnlinePrivilegeChecker_C final : public APlatformPrivilegeObject
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_OnlinePrivilegeChecker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_OnlinePrivilegeChecker_C")
	}
	static class ABP_OnlinePrivilegeChecker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OnlinePrivilegeChecker_C>();
	}
};
DUMPER7_ASSERTS_ABP_OnlinePrivilegeChecker_C;

}

