#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SaveDataSetting

#include "Basic.hpp"

#include "UNION_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SaveDataSetting.BP_SaveDataSetting_C
// 0x0020 (0x0328 - 0x0308)
class ABP_SaveDataSetting_C final : public ASaveDataSetting
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0308(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnFinished;                                        // 0x0318(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void AppDataResultDelegate_Event(bool bSuccess);
	void ConfigDataResultDelegate_Event(bool bSuccess);
	void ExecuteUbergraph_BP_SaveDataSetting(int32 EntryPoint);
	void NetDataResultDelegate_Event(bool bSuccess);
	void PlayLogDataResultDelegate_Event(bool bSuccess);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReplayDataResultDelegate_Event(bool bSuccess);
	void RetryAppData_Event();
	void RetryConfigData_Event();
	void RetryNetData_Event();
	void RetryPlayLogData_Event();
	void RetryReplayData_Event();
	void Start();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SaveDataSetting_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SaveDataSetting_C")
	}
	static class ABP_SaveDataSetting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SaveDataSetting_C>();
	}
};
DUMPER7_ASSERTS_ABP_SaveDataSetting_C;

}

