#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_RaceSequenceStateSendRaceStart

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionSystem_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.BindRecvLobbyAttributeEvent
// 0x0030 (0x0030 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_BindRecvLobbyAttributeEvent final
{
public:
	TDelegate<void(const class FString& InEntryRaceId)> K2Node_CreateDelegate_OutputDelegate;        // 0x0000(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNetDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyContextBase*                      CallFunc_GetPublicLobbyContext_ReturnValue;        // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonLobbyContext*                    K2Node_DynamicCast_AsCommon_Lobby_Context;         // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_BindRecvLobbyAttributeEvent;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.CalllNextState
// 0x0040 (0x0040 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_CalllNextState final
{
public:
	bool                                          CallFunc_IsShippingBuild_ReturnValue;              // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsShippingBuild_ReturnValue_1;            // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsShippingBuild_ReturnValue_2;            // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3[0x5];                                        // 0x0003(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetLastServerTime_ServerTime;             // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLastServerTime_ReturnValue;            // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FDateTime                              CallFunc_DateTimeFromString_Result;                // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DateTimeFromString_ReturnValue;           // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_CalllNextState;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.CheckResCode
// 0x0078 (0x0078 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_CheckResCode final
{
public:
	int32                                         InResCode;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          OutError;                                          // 0x0004(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 LogOutputInfo;                                     // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          bEnableChangeNextState;                            // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         ResCodeAbstract;                                   // 0x0019(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         OutResCode;                                        // 0x001C(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsShippingBuild_ReturnValue;              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_ValidateResCode_ResCodeAbstract;          // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ValidateResCode_ReturnValue;              // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_BoolToString_ReturnValue;            // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsShippingBuild_ReturnValue_1;            // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_CheckResCode;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.ConvertStickerData
// 0x0178 (0x0178 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_ConvertStickerData final
{
public:
	struct FUserStickerData                       UserStickerData;                                   // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FCommon_MachineStickerData             Common_MachineStickerData;                         // 0x0028(0x0068)(Parm, OutParm)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue;          // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue_1;        // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue_2;        // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue_3;        // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_DoubleToString_ReturnValue_4;        // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FCommon_MachineStickerData             K2Node_MakeStruct_Common_MachineStickerData;       // 0x00E8(0x0068)()
	double                                        CallFunc_Conv_DoubleToString_InDouble_ImplicitCast; // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_DoubleToString_InDouble_ImplicitCast_1; // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_DoubleToString_InDouble_ImplicitCast_2; // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_DoubleToString_InDouble_ImplicitCast_3; // 0x0168(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Conv_DoubleToString_InDouble_ImplicitCast_4; // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_ConvertStickerData;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.ExecuteUbergraph_BPC_RaceSequenceStateSendRaceStart
// 0x3190 (0x3190 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_ExecuteUbergraph_BPC_RaceSequenceStateSendRaceStart final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_MakeLiteralString_ReturnValue;            // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ApiName_4;                      // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_RequestData_4;                  // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ResponseData_4;                 // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Error_4;                        // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Parse_StartSaveFestaStart_ResCode;        // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveFestaStartResponse           CallFunc_Parse_StartSaveFestaStart_Response;       // 0x0050(0x0058)()
	class FString                                 CallFunc_MakeLiteralString_ReturnValue_1;          // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	EGameModeId                                   CallFunc_GetSelectedGameModeId_ReturnValue;        // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         K2Node_MakeArray_Array;                            // 0x00C0(0x0010)(ReferenceParm)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue;                      // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x00D3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetBonusChanceData_IsValid;               // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetBonusChanceData_BonusChanceType;       // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBonusChanceData_BonusChanceParam;      // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_MakeLiteralString_ReturnValue_2;          // 0x00E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckResCode_bEnableChangeNextState;      // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_CheckResCode_ResCodeAbstract;             // 0x00F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F2[0x2];                                       // 0x00F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CheckResCode_OutResCode;                  // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_MakeLiteralString_ReturnValue_3;          // 0x00F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ApiName_5;                      // 0x0108(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_RequestData_5;                  // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ResponseData_5;                 // 0x0128(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Error_5;                        // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_139[0x3];                                      // 0x0139(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommon_FestaBonusChanceData           K2Node_MakeStruct_Common_FestaBonusChanceData;     // 0x013C(0x0008)(NoDestructor)
	int32                                         CallFunc_Parse_StartSaveFestaStart_ResCode_1;      // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveFestaStartResponse           CallFunc_Parse_StartSaveFestaStart_Response_1;     // 0x0148(0x0058)()
	class FString                                 K2Node_CustomEvent_InEntryRaceId;                  // 0x01A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckResCode_bEnableChangeNextState_1;    // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_CheckResCode_ResCodeAbstract_1;           // 0x01B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B2[0x2];                                      // 0x01B2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CheckResCode_OutResCode_1;                // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCommon_FestaBonusChanceData           K2Node_MakeStruct_Common_FestaBonusChanceData_1;   // 0x01B8(0x0008)(NoDestructor)
	struct FCommon_FestaBonusChanceData           K2Node_MakeStruct_Common_FestaBonusChanceData_2;   // 0x01C0(0x0008)(NoDestructor)
	class FString                                 K2Node_CustomEvent_ApiName_3;                      // 0x01C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_RequestData_3;                  // 0x01D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ResponseData_3;                 // 0x01E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Error_3;                        // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F9[0x3];                                      // 0x01F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Parse_StartSaveFestaStart_ResCode_2;      // 0x01FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveFestaStartResponse           CallFunc_Parse_StartSaveFestaStart_Response_2;     // 0x0200(0x0058)()
	bool                                          CallFunc_CheckResCode_bEnableChangeNextState_2;    // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_CheckResCode_ResCodeAbstract_2;           // 0x0259(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25A[0x2];                                      // 0x025A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CheckResCode_OutResCode_2;                // 0x025C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CharacterId;     // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CourseId;        // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCommon_MachineData                    CallFunc_GetStartSaveRequestParam_MachineData;     // 0x0268(0x0370)()
	struct FCommon_GadgetData                     CallFunc_GetStartSaveRequestParam_GadgetData;      // 0x05D8(0x001C)(NoDestructor)
	struct FCommon_DegreeData                     CallFunc_GetStartSaveRequestParam_DegreeData;      // 0x05F4(0x0008)(NoDestructor)
	int32                                         CallFunc_GetStartSaveRequestParam_CharacterId_1;   // 0x05FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CourseId_1;      // 0x0600(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_604[0x4];                                      // 0x0604(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommon_MachineData                    CallFunc_GetStartSaveRequestParam_MachineData_1;   // 0x0608(0x0370)()
	struct FCommon_GadgetData                     CallFunc_GetStartSaveRequestParam_GadgetData_1;    // 0x0978(0x001C)(NoDestructor)
	struct FCommon_DegreeData                     CallFunc_GetStartSaveRequestParam_DegreeData_1;    // 0x0994(0x0008)(NoDestructor)
	uint8                                         Pad_99C[0x4];                                      // 0x099C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UOnlineMatchSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x09A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EGameModeId                                   CallFunc_GetSelectedGameModeId_ReturnValue_1;      // 0x09A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEnableOnlineSinglePlay_ReturnValue;     // 0x09A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x09AA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9AB[0x5];                                      // 0x09AB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UNetMasterDataManageSubsystem*          CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x09B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetFestaIdUtil_ReturnValue;               // 0x09B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLegendCompeId_ReturnValue;             // 0x09BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveFestaStartRequest            K2Node_MakeStruct_StartSaveFestaStartRequest;      // 0x09C0(0x03A8)()
	int32                                         CallFunc_GetFestaIdUtil_ReturnValue_1;             // 0x0D68(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CharacterId_2;   // 0x0D6C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CourseId_2;      // 0x0D70(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D74[0x4];                                      // 0x0D74(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommon_MachineData                    CallFunc_GetStartSaveRequestParam_MachineData_2;   // 0x0D78(0x0370)()
	struct FCommon_GadgetData                     CallFunc_GetStartSaveRequestParam_GadgetData_2;    // 0x10E8(0x001C)(NoDestructor)
	struct FCommon_DegreeData                     CallFunc_GetStartSaveRequestParam_DegreeData_2;    // 0x1104(0x0008)(NoDestructor)
	int32                                         CallFunc_GetStartSaveRequestParam_CharacterId_3;   // 0x110C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CourseId_3;      // 0x1110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1114[0x4];                                     // 0x1114(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommon_MachineData                    CallFunc_GetStartSaveRequestParam_MachineData_3;   // 0x1118(0x0370)()
	struct FCommon_GadgetData                     CallFunc_GetStartSaveRequestParam_GadgetData_3;    // 0x1488(0x001C)(NoDestructor)
	struct FCommon_DegreeData                     CallFunc_GetStartSaveRequestParam_DegreeData_3;    // 0x14A4(0x0008)(NoDestructor)
	uint8                                         Pad_14AC[0x4];                                     // 0x14AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStartSaveFestaStartRequest            K2Node_MakeStruct_StartSaveFestaStartRequest_1;    // 0x14B0(0x03A8)()
	class UOnlineMatchSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue_2;   // 0x1858(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UOnlineMatchSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue_3;   // 0x1860(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEnableOnlineSinglePlay_ReturnValue_1;   // 0x1868(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEnableOnlineSinglePlay_ReturnValue_2;   // 0x1869(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_186A[0x6];                                     // 0x186A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_MakeLiteralString_ReturnValue_4;          // 0x1870(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UNetMasterDataManageSubsystem*          CallFunc_GetGameInstanceSubsystem_ReturnValue_4;   // 0x1880(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLegendCompeId_ReturnValue_1;           // 0x1888(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& ApiName, const class FString& RequestData, const class FString& ResponseData, bool Error)> K2Node_CreateDelegate_OutputDelegate; // 0x188C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& ApiName, const class FString& RequestData, const class FString& ResponseData, bool Error)> K2Node_CreateDelegate_OutputDelegate_1; // 0x189C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& ApiName, const class FString& RequestData, const class FString& ResponseData, bool Error)> K2Node_CreateDelegate_OutputDelegate_2; // 0x18AC(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18BC[0x4];                                     // 0x18BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         K2Node_MakeArray_Array_1;                          // 0x18C0(0x0010)(ReferenceParm)
	class FString                                 K2Node_CustomEvent_ApiName_2;                      // 0x18D0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_RequestData_2;                  // 0x18E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ResponseData_2;                 // 0x18F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Error_2;                        // 0x1900(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1901[0x3];                                     // 0x1901(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Parse_StartSaveRankMatchStart_ResCode;    // 0x1904(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveRankMatchStartResponse       CallFunc_Parse_StartSaveRankMatchStart_Response;   // 0x1908(0x0010)()
	int32                                         CallFunc_GetStartSaveRequestParam_CharacterId_4;   // 0x1918(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CourseId_4;      // 0x191C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCommon_MachineData                    CallFunc_GetStartSaveRequestParam_MachineData_4;   // 0x1920(0x0370)()
	struct FCommon_GadgetData                     CallFunc_GetStartSaveRequestParam_GadgetData_4;    // 0x1C90(0x001C)(NoDestructor)
	struct FCommon_DegreeData                     CallFunc_GetStartSaveRequestParam_DegreeData_4;    // 0x1CAC(0x0008)(NoDestructor)
	bool                                          CallFunc_CheckResCode_bEnableChangeNextState_3;    // 0x1CB4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_CheckResCode_ResCodeAbstract_3;           // 0x1CB5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CB6[0x2];                                     // 0x1CB6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CheckResCode_OutResCode_3;                // 0x1CB8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CBC[0x4];                                     // 0x1CBC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAppSequenceLogManagerSubsystem*        CallFunc_GetGameInstanceSubsystem_ReturnValue_5;   // 0x1CC0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ApiName_1;                      // 0x1CC8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_RequestData_1;                  // 0x1CD8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ResponseData_1;                 // 0x1CE8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Error_1;                        // 0x1CF8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CF9[0x3];                                     // 0x1CF9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Parse_StartSaveLegendCompeStart_ResCode;  // 0x1CFC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveLegendCompeStartResponse     CallFunc_Parse_StartSaveLegendCompeStart_Response; // 0x1D00(0x0010)()
	class FString                                 CallFunc_MakeLiteralString_ReturnValue_5;          // 0x1D10(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckResCode_bEnableChangeNextState_4;    // 0x1D20(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_CheckResCode_ResCodeAbstract_4;           // 0x1D21(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D22[0x2];                                     // 0x1D22(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CheckResCode_OutResCode_4;                // 0x1D24(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAppSequenceLogManagerSubsystem*        CallFunc_GetGameInstanceSubsystem_ReturnValue_6;   // 0x1D28(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	ESequenceSubType                              CallFunc_GetSequenceSubType_ReturnValue;           // 0x1D30(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESequenceMainType                             CallFunc_GetSequenceMainType_ReturnValue;          // 0x1D31(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D32[0x6];                                     // 0x1D32(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_ApiName;                        // 0x1D38(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_RequestData;                    // 0x1D48(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_ResponseData;                   // 0x1D58(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Error;                          // 0x1D68(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D69[0x3];                                     // 0x1D69(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Parse_StartSaveLegendCompeStart_ResCode_1; // 0x1D6C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveLegendCompeStartResponse     CallFunc_Parse_StartSaveLegendCompeStart_Response_1; // 0x1D70(0x0010)()
	TDelegate<void(const class FString& ApiName, const class FString& RequestData, const class FString& ResponseData, bool Error)> K2Node_CreateDelegate_OutputDelegate_3; // 0x1D80(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckResCode_bEnableChangeNextState_5;    // 0x1D90(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EResponseCodeAbstract                         CallFunc_CheckResCode_ResCodeAbstract_5;           // 0x1D91(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D92[0x2];                                     // 0x1D92(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_CheckResCode_OutResCode_5;                // 0x1D94(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAppSequenceLogManagerSubsystem*        CallFunc_GetGameInstanceSubsystem_ReturnValue_7;   // 0x1D98(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EGameModeId                                   CallFunc_GetSelectedGameModeId_ReturnValue_2;      // 0x1DA0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CheckSkipCurrentState_ReturnValue;        // 0x1DA1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_2;                    // 0x1DA2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1DA3[0x5];                                     // 0x1DA3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAppDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue_8;   // 0x1DA8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAppDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue_9;   // 0x1DB0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_MakeLiteralInt_ReturnValue;               // 0x1DB8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1DBC[0x4];                                     // 0x1DBC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FCommon_UserRateData>           CallFunc_MakeRateData_OutUserRateData;             // 0x1DC0(0x0010)(ReferenceParm)
	struct FStartSaveRankMatchStartRequest        K2Node_MakeStruct_StartSaveRankMatchStartRequest;  // 0x1DD0(0x03D8)()
	TArray<struct FCommon_UserRateData>           CallFunc_MakeRateData_OutUserRateData_1;           // 0x21A8(0x0010)(ReferenceParm)
	struct FStartSaveRankMatchStartRequest        K2Node_MakeStruct_StartSaveRankMatchStartRequest_1; // 0x21B8(0x03D8)()
	TArray<struct FCommon_UserRateData>           CallFunc_MakeRateData_OutUserRateData_2;           // 0x2590(0x0010)(ReferenceParm)
	class UAppDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue_10;  // 0x25A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FStartSaveLegendCompeStartRequest      K2Node_MakeStruct_StartSaveLegendCompeStartRequest; // 0x25A8(0x03E0)()
	bool                                          CallFunc_NotEqual_StrStr_ReturnValue;              // 0x2988(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2989[0x3];                                     // 0x2989(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& ApiName, const class FString& RequestData, const class FString& ResponseData, bool Error)> K2Node_CreateDelegate_OutputDelegate_4; // 0x298C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299C[0x4];                                     // 0x299C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FCommon_UserRateData>           CallFunc_MakeRateData_OutUserRateData_3;           // 0x29A0(0x0010)(ReferenceParm)
	class UNetDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue_11;  // 0x29B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyContextBase*                      CallFunc_GetPublicLobbyContext_ReturnValue;        // 0x29B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonLobbyContext*                    K2Node_DynamicCast_AsCommon_Lobby_Context;         // 0x29C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x29C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29C9[0x3];                                     // 0x29C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetStartSaveRequestParam_CharacterId_5;   // 0x29CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetStartSaveRequestParam_CourseId_5;      // 0x29D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29D4[0x4];                                     // 0x29D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommon_MachineData                    CallFunc_GetStartSaveRequestParam_MachineData_5;   // 0x29D8(0x0370)()
	struct FCommon_GadgetData                     CallFunc_GetStartSaveRequestParam_GadgetData_5;    // 0x2D48(0x001C)(NoDestructor)
	struct FCommon_DegreeData                     CallFunc_GetStartSaveRequestParam_DegreeData_5;    // 0x2D64(0x0008)(NoDestructor)
	uint8                                         Pad_2D6C[0x4];                                     // 0x2D6C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetLobbyAttributeEntryRaceId_OutRaceId;   // 0x2D70(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetLobbyAttributeEntryRaceId_ReturnValue; // 0x2D80(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D81[0x7];                                     // 0x2D81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEntryRaceId_ReturnValue;               // 0x2D88(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEmpty_ReturnValue_1;                    // 0x2D98(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x2D99(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D9A[0x6];                                     // 0x2D9A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FStartSaveLegendCompeStartRequest      K2Node_MakeStruct_StartSaveLegendCompeStartRequest_1; // 0x2DA0(0x03E0)()
	TDelegate<void(const class FString& ApiName, const class FString& RequestData, const class FString& ResponseData, bool Error)> K2Node_CreateDelegate_OutputDelegate_5; // 0x3180(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_ExecuteUbergraph_BPC_RaceSequenceStateSendRaceStart;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.FinishedSendStartSaveFestaStart_Event
// 0x0038 (0x0038 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_FinishedSendStartSaveFestaStart_Event final
{
public:
	class FString                                 ApiName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 RequestData;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ResponseData;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Error;                                             // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_FinishedSendStartSaveFestaStart_Event;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.FinishedSendStartSaveLegendCompeStart
// 0x0038 (0x0038 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_FinishedSendStartSaveLegendCompeStart final
{
public:
	class FString                                 ApiName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 RequestData;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ResponseData;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Error;                                             // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_FinishedSendStartSaveLegendCompeStart;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.FinishedSendStartSaveRankMatchStart_Event
// 0x0038 (0x0038 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_FinishedSendStartSaveRankMatchStart_Event final
{
public:
	class FString                                 ApiName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 RequestData;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ResponseData;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Error;                                             // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_FinishedSendStartSaveRankMatchStart_Event;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.GetBonusChanceData
// 0x0038 (0x0038 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_GetBonusChanceData final
{
public:
	bool                                          IsValid;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         BonusChanceType_0;                                 // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BonusChanceParam_0;                                // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNetDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyContextBase*                      CallFunc_GetPublicLobbyContext_ReturnValue;        // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UFestaLobbyContext*                     K2Node_DynamicCast_AsFesta_Lobby_Context;          // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetBonusChanceData_BonusChanceType;       // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetBonusChanceData_BonusChanceParam;      // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetBonusChanceData_ReturnValue;           // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_GetBonusChanceData;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.GetLobbyContextParam
// 0x00D0 (0x00D0 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_GetLobbyContextParam final
{
public:
	class UNetDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyContextBase*                      CallFunc_GetPublicLobbyContext_ReturnValue;        // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonLobbyContext*                    K2Node_DynamicCast_AsCommon_Lobby_Context;         // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLobbyId                               CallFunc_GetLobbyId_ReturnValue;                   // 0x0020(0x0010)(ConstParm)
	class FString                                 CallFunc_ConvertLobbyIdToString_OutUserIdString;   // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsRaceHostLocalUser_ReturnValue;          // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_SelectString_ReturnValue;                 // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FUniqueNetIdRepl                       CallFunc_GetLocalUserId_OutUserId;                 // 0x0058(0x0030)(HasGetValueTypeHash)
	class ULobbyMemberContextBase*                CallFunc_GetHostMember_ReturnValue;                // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyMemberContextBase*                CallFunc_GetMember_ReturnValue;                    // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0099(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9A[0x6];                                       // 0x009A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonLobbyContext*                    K2Node_DynamicCast_AsCommon_Lobby_Context_1;       // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         CallFunc_GetOnlineEntryUserIds_OutAllUserIds;      // 0x00B0(0x0010)(ReferenceParm)
	TArray<class FString>                         CallFunc_GetOnlineEntryUserIds_OutPlayerUserIds;   // 0x00C0(0x0010)(ReferenceParm)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_GetLobbyContextParam;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.GetStartSaveRequestParam
// 0x0AE0 (0x0AE0 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_GetStartSaveRequestParam final
{
public:
	int32                                         characterId;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         courseId;                                          // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCommon_MachineData                    MachineData;                                       // 0x0008(0x0370)(Parm, OutParm)
	struct FCommon_GadgetData                     GadgetData;                                        // 0x0378(0x001C)(Parm, OutParm, NoDestructor)
	struct FCommon_DegreeData                     DegreeData;                                        // 0x0394(0x0008)(Parm, OutParm, NoDestructor)
	struct FCommon_DegreeData                     LocalDegreeData;                                   // 0x039C(0x0008)(Edit, BlueprintVisible, NoDestructor)
	struct FCommon_GadgetData                     LocalGadgetData;                                   // 0x03A4(0x001C)(Edit, BlueprintVisible, NoDestructor)
	struct FCommon_MachineData                    LocalMachineData;                                  // 0x03C0(0x0370)(Edit, BlueprintVisible)
	int32                                         LocalCourseId;                                     // 0x0730(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         LocalCharacterId;                                  // 0x0734(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MyPlayerIndex;                                     // 0x0738(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EDriverId                                     CallFunc_GetRaceRequestData_OutDriverId;           // 0x073C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EStageId                                      CallFunc_GetRaceRequestData_OutMainStageId;        // 0x073D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_73E[0x2];                                      // 0x073E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCommon_MachineData                    CallFunc_GetRaceRequestData_OutMachineCustomizeData; // 0x0740(0x0370)()
	struct FCommon_GadgetData                     CallFunc_GetRaceRequestData_OutGadgetPlateData;    // 0x0AB0(0x001C)(NoDestructor)
	struct FCommon_DegreeData                     CallFunc_GetRaceRequestData_OutDegreeData;         // 0x0ACC(0x0008)(NoDestructor)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0AD4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x0AD8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_GetStartSaveRequestParam;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.OccurServerError
// 0x0008 (0x0008 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_OccurServerError final
{
public:
	EResponseCodeAbstract                         ResponseCode;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Code;                                              // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_OccurServerError;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.OnRecvEntryRaceId
// 0x0010 (0x0010 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_OnRecvEntryRaceId final
{
public:
	class FString                                 InEntryRaceId;                                     // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_OnRecvEntryRaceId;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.OnSendStartSaveFestaStartCallback
// 0x0038 (0x0038 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_OnSendStartSaveFestaStartCallback final
{
public:
	class FString                                 ApiName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 RequestData;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ResponseData;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Error;                                             // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_OnSendStartSaveFestaStartCallback;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.OnSendStartSaveLegendCompeStartCallback
// 0x0038 (0x0038 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_OnSendStartSaveLegendCompeStartCallback final
{
public:
	class FString                                 ApiName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 RequestData;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ResponseData;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Error;                                             // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_OnSendStartSaveLegendCompeStartCallback;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.OnSendStartSaveRankMatchStartCallback
// 0x0038 (0x0038 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_OnSendStartSaveRankMatchStartCallback final
{
public:
	class FString                                 ApiName;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 RequestData;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 ResponseData;                                      // 0x0020(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Error;                                             // 0x0030(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_OnSendStartSaveRankMatchStartCallback;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.StartPlatformGameMatch
// 0x0030 (0x0030 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_StartPlatformGameMatch final
{
public:
	EGameModeId                                   CallFunc_GetSelectedGameModeId_ReturnValue;        // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNetDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ULobbyContextBase*                      CallFunc_GetPublicLobbyContext_ReturnValue;        // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonLobbyContext*                    K2Node_DynamicCast_AsCommon_Lobby_Context;         // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_StartPlatformGameMatch;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.SyncEntryRaceId
// 0x0028 (0x0028 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_SyncEntryRaceId final
{
public:
	class UNetDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyContextBase*                      CallFunc_GetPublicLobbyContext_ReturnValue;        // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyMemberContextBase*                CallFunc_GetLocalMember_ReturnValue;               // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonLobbyMemberContext*              K2Node_DynamicCast_AsCommon_Lobby_Member_Context;  // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_SyncEntryRaceId;

// Function BPC_RaceSequenceStateSendRaceStart.BPC_RaceSequenceStateSendRaceStart_C.SyncEntryRaceIdForFesta
// 0x0030 (0x0030 - 0x0000)
struct BPC_RaceSequenceStateSendRaceStart_C_SyncEntryRaceIdForFesta final
{
public:
	struct FCommon_FestaBonusChanceData           K2Node_MakeStruct_Common_FestaBonusChanceData;     // 0x0000(0x0008)(NoDestructor)
	class UNetDataManageSubsystem*                CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyContextBase*                      CallFunc_GetPublicLobbyContext_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULobbyMemberContextBase*                CallFunc_GetLocalMember_ReturnValue;               // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UFestaLobbyMemberContext*               K2Node_DynamicCast_AsFesta_Lobby_Member_Context;   // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPC_RaceSequenceStateSendRaceStart_C_SyncEntryRaceIdForFesta;

}

